import argparse
import sys

parser = argparse.ArgumentParser()
arg = parser.add_argument
arg('--epochs', type=int, default=300)
arg('--fold', default='0,1,2,3,4')
arg('--n_folds', type=int, default=5)
arg('--freeze_till_layer', default='input_1')
arg('--preprocessing_function', default='resnet50')
arg('--weights')
arg('--learning_rate', type=float, default=0.0001)
arg('--initial_size', type=int, default=101)
arg('--input_size', type=int, default=128)
arg('--batch_size', type=int, default=20)
arg('--num_workers', type=int, default=8)
arg('--loss_function', default='bce_jacard')
arg('--optimizer', default='rmsprop')
arg('--augmentation_name', default='initial')
arg('--augmentation_prob', type=float, default=0.9)
arg('--clr')
arg('--decay', type=float, default=0.0)
arg('--network', default='resnet50_fpn')
arg('--alias', default='_128_padding')
arg('--models_dir', default='/home/branding_images/salt/')
arg('--images_dir', default='/home/p/babakhin/Branding/salt/train/images')
arg('--masks_dir', default='/home/p/babakhin/Branding/salt/train/masks')
arg('--test_folder', default='/home/p/babakhin/Branding/salt/test/images')
arg('--folds_csv', default='data/train_proc_v2.csv')
arg('--out_root_dir', default='submissions/')
arg('--models',  nargs='+')
arg('--callback', default='reduce_lr')
arg('--early_stop_patience',  type=int, default=10)
arg('--reduce_lr_factor',  type=float, default=0.25)
arg('--reduce_lr_patience',  type=int, default=5)
arg('--reduce_lr_min',  type=float, default=0.000001)
arg('--TTA', default='')

sys.argv = ['foo']
args = parser.parse_args()