import argparse
import sys

parser = argparse.ArgumentParser()
arg = parser.add_argument
arg('--epochs', type=int, default=300)
arg('--fold', default='0')
arg('--n_folds', type=int, default=5)
# arg('--freeze_till_layer', default='input_1')
# arg('--preprocessing_function', default='resnet50')
# arg('--weights', default='/home/branding_images/salt/unet_resnet_34_do_exp_0_resize_144_pad_192_do_04_02_middle_checkpoint_corr_again/fold_{}.hdf5')
arg('--weights')
arg('--learning_rate', type=float, default=0.0001)
arg('--initial_size', type=int, default=101)
arg('--input_size', type=int, default=192)
arg('--resize_size', type=int, default=144)
arg('--batch_size', type=int, default=32)
arg('--num_workers', type=int, default=8)
arg('--loss_function', default='bce_jacard')
#arg('--loss_function', default='lovasz')
arg('--optimizer', default='rmsprop')
arg('--augmentation_name', default='valid_plus')
arg('--augmentation_prob', type=float, default=1.0)
#arg('--network', default='unet_resnet_152,resnet152_fpn')
#arg('--alias', default='_exp_0_resize_144_pad_192')
arg('--network', default='unet_resnet_34')
arg('--alias', default='_exp_0_resize_144_pad_192_cyclic_lr_metric_checkpoint_v1')
#arg('--alias', default='_valid_plus_resize_202_pad_256_bs_12_corr')
arg('--models_dir', default='/home/branding_images/salt/')
arg('--images_dir', default='/home/p/babakhin/Branding/salt/train/images')
arg('--masks_dir', default='/home/p/babakhin/Branding/salt/train/masks')
arg('--test_folder', default='/home/p/babakhin/Branding/salt/test/images')
arg('--folds_csv', default='data/train_proc_v2.csv')
arg('--out_root_dir', default='submissions/')
arg('--models',  nargs='+')
arg('--callback', default='cyclic_lr')
arg('--early_stop_patience',  type=int, default=10)
arg('--reduce_lr_factor',  type=float, default=0.25)
arg('--reduce_lr_patience',  type=int, default=5)
arg('--reduce_lr_min',  type=float, default=0.000001)
arg('--TTA', default='')

sys.argv = ['foo']
args = parser.parse_args()

